# Site settings
title: K9 4 Keeps
email: info@k94keeps.org
description: >
  K9 4 KEEPS believes that bringing a dog into your family should be forever.
  For keeps. We are a 100% volunteer run, 501(c)(3) non-profit organization
  dedicated to dog rescue. We believe rescue should begin with education and
  counseling of dog owners regarding proper handling and training of their dogs
  to support positive, forever relationships. K9 4 KEEPS dogs are surrendered by
  their owners or rescued from Chicagoland area kill shelters and are provided
  vetting, housing, foster and adoption services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://k94keeps.org"
twitter_username: k94keeps
facebook_username: k94keeps
instagram_username: k94keeps

# Collections
#collections:
#  dogs:
#    output: true
#  events:
#    output: true

# Page defaults
defaults:
  - scope:
      path: "dogs/index.md"
    values:
      layout: "default"
      type: "index"
  - scope:
      path: "dogs"
    values:
      layout: "dog"
      type: "dog"
  - scope:
      path: "events/index.md"
    values:
      layout: "default"
      type: "index"
  - scope:
      path: "events"
    values:
      layout: "event"
      type: "event"

# Build settings
markdown: kramdown
safe: true

plugins:
  - jekyll-sitemap

